apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-todo-app-deployment
  labels:
    app: flask-todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-todo-app
  template:
    metadata:
      labels:
        app: flask-todo-app
    spec:
      containers:
      - name: flask-todo-app
        image: gilad88/flask-todo-app:latest # שנה ליוזר שלך בדוקר
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          value: postgresql://user:password@flask-todo-db-service:5432/todoapp
---
apiVersion: v1
kind: Service
metadata:
  name: flask-todo-app-service
  labels:
    app: flask-todo-app
spec:
  selector:
    app: flask-todo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
